# Matrices

### Ahora, enfoquemonos en matrices, recordar que acomparacion de los vectores, las matrices tienen filas y columnas por lo que son arrays 2D, es decir dos dimenciones, una dimension fila y la otra dimension columna, ahora empecemos con lo basico, como se escribe o se crea una matriz con numpy, 

#### ahora como la creamos o cual es su sintaxis? recordemos que un vector es un renglon (1D), entonces las matrices seran dos vectores por decirlo de alguna forma, por lo tanto la sintaxis son matriz = np.array ([[ ]]), listas dentro de listas o vectores dentro de una lista

In [2]:
# los corchetes exteriores, son los que agrupan toda la tabla,
#los interiores, agrupan la fila
import numpy as np
#cramos la matriz
primera_matriz = np.array([
    [1,2,3], #esta es la fila 0
    [4,5,6], # fila 1
    [7,8,9] #fila 2
])
print("Mi matriz manual:\n", primera_matriz)

Mi matriz manual:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#aplicamos la funcion .shape, para que nos diga la dimension del array
primera_matriz.shape

(3, 3)

In [4]:
#ahora la funcion .ndim, nos dice que el array es de dos dimenciones eso ya lo sabiamos
primera_matriz.ndim


2

### FUNCION .reshape(), IMPORTANTE

#### Que hace esta funcion ? la parte tecnica; Esta función sirve para reorganizar los datos de un arreglo en nuevas dimensiones sin cambiar ni borrar la información que contiene.
#### hagamos una analogia, pensemos que tenemos un vector de 12 datos, quiere decir que lo tenemos en un renglon 1D , con esta funcion, podemos transformar ese renglon , en un rectangulo o basicamente en una matriz que es de dos dimenciones 2D

#### REGLA DE ORO: para que funcione .reshape(), el numero total de elementos debe ser el mismo antes y despues de transformarse, si tu valor inicial es de 12 elementos o tu vector suponiendo, tu matriz debe de tener el mismo numero de elementos , esa matriz puede ser de 4X3, 3X4, 6x2 etc, si no concide con el numero total de datos, numpy te dara error.

In [6]:
# Sintaxis de la funcion, solo ponemos al final .rshape y dentro filas y columnas
#nuevo_arreglo = arreglo_original.reshape(numero_de_filas, numero_de_columnas)
#veamos un ejemplo simple pero real 
vector_original = np.array([1,2,3,4,5,6])
#aplicamos la funcion
vector_nuevo = vector_original.reshape(2,3)
print(vector_nuevo)




[[1 2 3]
 [4 5 6]]


# Slicing avanzado, aplicado a matrices

#### Al igual que vimos en vectores, el Slicing es una tecnica o un metodo para extraer cierto numero de datos o "rebanada", estas tecnicas son practicamente navegacion, por ejemplo "dame la columna uno", etc, recordemos que usamos una sintaxis muy parecida a la que usamos en las listas de python

##### Formula maestra , matriz[Rebanada_filas , Rebanada_columnas]

In [10]:
# Si quieres TODAS las filas y TODAS las columnas, solo ponemos dos puntos :
matrizA = np.array([1,2,3,4,5,6,7,8,9])
matrizB = matrizA.reshape(3,3)
print(matrizB)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# Extraer un solo dato, fila 0, columna 2
dato_1 = matrizB[0,2]
print(dato_1)

3


In [15]:
#extraemos una fila completa, la cero, ponemos el la fila, separamos por coma y ponemos :, para que traiga toda la fila
fila_1 = matrizB[0, :]
print(fila_1)

[1 2 3]


In [22]:
#para la columna, solo invertimos la sintaxis anterior, dejamos vacio el hueco de filas, y ponemos el numero de la columna
# queremos
columna_2 = matrizB[: ,2]
print(columna_2)

[3 6 9]


In [24]:
#para la columna cero
columna_0 = matrizB[:,0]
print("\nToda la columna 0:\n", columna_0)



Toda la columna 0:
 [1 4 7]


# OPERACIONES Matematicas


In [25]:
# Dos vectores simples
ventas_enero = np.array([100, 200, 300])
ventas_febrero = np.array([50, 100, 150])

# 1. Suma directa entre vectores (suma posición por posición)
ventas_totales = ventas_enero + ventas_febrero
print("Suma de vectores:", ventas_totales)

# 2. Operaciones con un número suelto (Escalar)
# Ejemplo: Queremos multiplicar todas las ventas de enero por 2
ventas_dobles = ventas_enero * 2
print("Multiplicación por 2 en todo el vector:\n", ventas_dobles)

# 3. Lo mismo funciona con matrices 2D
matriz_base = np.array([[1, 2], [3, 4]])
matriz_mas_diez = matriz_base + 10
print("\nMatriz sumándole 10 a todo:\n", matriz_mas_diez)

Suma de vectores: [150 300 450]
Multiplicación por 2 en todo el vector:
 [200 400 600]

Matriz sumándole 10 a todo:
 [[11 12]
 [13 14]]


#### Broadcasting, bien ahora , antes de pasar a ver cada operacion a profundidad, expliquemos el broadcasting, en el punto numero tres del codigo, anterior lo que paso fue que sumamos el numero 10, a todas las partes de la matriz, a esto se le conoce como broadcasting, ligando un poco la palabra se refiere a difusion, y lo que hicimos fue difunfir ese 10, en todos los elementos de las matriz y lo sumamos.

#### Practiquemos, el broadcasting, EJERCICIO 1: Imagina que tienes el registro de tus ingresos y tus costos operativos de los últimos 4 meses. Queremos sacar la ganancia neta y el margen de ganancia en porcentaje.

In [3]:
import numpy as np

# Datos
ingresos = np.array([5000, 7000, 6500, 8000])
costos = np.array([3000, 4500, 4000, 5000])

# Tu misión:
# 1. Crea una variable llamada 'ganancias' que reste los costos a los ingresos.
# 2. Crea una variable 'margen_porcentaje' dividiendo las ganancias entre los ingresos, y multiplicando el resultado por 100.
# 3. Imprime ambos resultados.
ganancias = ingresos - costos
print("Ganancia Neta: ", ganancias)

margen_porcentaje = (ganancias / ingresos) * 100
print(margen_porcentaje)

Ganancia Neta:  [2000 2500 2500 3000]
[40.         35.71428571 38.46153846 37.5       ]


In [4]:
# Unidades vendidas (Matriz 2x3: 2 días, 3 productos)
unidades_vendidas = np.array([
    [10, 5, 8],  # Día 1
    [15, 8, 12]  # Día 2
])

# Precio unitario de los 3 productos (Vector 1D)
precios = np.array([20, 50, 15])

# Tu misión:
# 1. Multiplica 'unidades_vendidas' por 'precios' y guárdalo en una variable 'ingresos_diarios'. 
# (Observa cómo NumPy "estira" el vector de precios para multiplicar la fila del Día 1 y luego la fila del Día 2 automáticamente).
ingresos_diarios = unidades_vendidas * precios
print("Ingresos diarios x producto: ", ingresos_diarios)


Ingresos diarios x producto:  [[200 250 120]
 [300 400 180]]


# Algebra Lineal Real, Producto Punto

#### A diferencia de la multiplicación "elemento por elemento" que acabamos de ver, el Producto Punto (o multiplicación de matrices) es la que se usa en las matemáticas puras. Aquí no multiplicamos "posición 1 con posición 1", sino que cruzamos las filas de la primera matriz contra las columnas de la segunda.

#### Para que quede súper claro, vamos a usar un ejemplo de ventas y costos. Aquí tienes el código, y justo abajo, el desglose línea por línea como lo pediste.

In [5]:
import numpy as np

# Matriz 1: Unidades vendidas (Filas = Días, Columnas = Productos)
ventas = np.array([
    [10, 5],  # Día 1: 10 unidades del prod. A, 5 del prod. B
    [20, 8]   # Día 2: 20 unidades del prod. A, 8 del prod. B
])

# Matriz 2: Valores en pesos (Filas = Productos, Columnas = Precio de Venta, Costo de Producción)
valores = np.array([
    [50, 30], # Producto A: Se vende en $50, cuesta $30 hacerlo
    [15, 10]  # Producto B: Se vende en $15, cuesta $10 hacerlo
])

# Calculando el Producto Punto
totales = np.dot(ventas, valores)

# Imprimiendo el resultado
print(totales)

[[ 575  350]
 [1120  680]]


#### bien, aqui el tema que yo tenia no era el metodo de cruzar las matrices o hablandolo mas tecnico el proceso de multiplicar, mi problema era la interpretacion porque pienso que no sirve de nada, saber hacer la operacion si no se sabe interpretar, asi que , aqui va mi interpretacion, de la matriz resultante de multiplicar la matriz de ventas con la de valores, los 4 datos que nos da esa matriz son 575 que son el total de ventas al precio que le cuesta al publico tanto producto A y B, es decir aqui en este dato ya van los dos productos,el dato de 350, es el total del costo que cuesta hacer los productos A y B, por decirlo de alguna forma es la venta total y el otro dato lo que costo esa venta, OJO solo teniendo en cuenta el costo del producto no ls gastos operativos, esos dos datos que te di 575 y 350 son el renglon 1 que vendrian siendo el primer dia y aplica la misma logica para el segundo renglon, por lo tanto yo llamaria a la matriz resultante ventas_costo

# Estadistica Rapida


### Sumatoria total , funcion .sum(), esta funcion nos sirve para sumar todos los valores, si aplicamos solo esta funcion, esta suma todos los valores de la matriz sin importat cuantas filas y columnas tenga, sintaxis tuarray.sum().

In [4]:
# ejemplo de uso de funcion array 
import numpy as np
ventas_producto = np.array([
    [575 , 350],
    [1120 , 680]
    ])
print(ventas_producto.sum())

2725


#### Promedio o media, .mean(), esta funcion se encarga de sacar el promedio de una matriz, haciendo la operacion matematica del promedio que consiste en sumar todos los datos de la matriz o array y dividirlos entre el numero de datos totales. SINTAXIS tuarray.mean()


In [6]:
print(ventas_producto.mean())

681.25


#### Valor maximo, .max(), esta funcion es de las mas usadas en la libreria, basicamente lo que hace es extraer el valor mas grande de la matriz o array, util para encontrar el dia con mas venta o el producto mas caro, SINTAXIS .max()

In [8]:
#Sacamos el valor mas grande de la matriz ventas_producto
print(ventas_producto.max())
# si nos fijamos el dia 2 se vendio en mayor cantidad el producto A que el b, y tambien se vendio mas que el dia 1

1120


#### Valor minimo, .min(), esta funcion al igual que la anterior, es una de las funciones mas usadas, y contrario a la anterior, esta busca y arroja el valor mas pequeño en toda la matriz o array, SINTAXIS .min(), . Sirve para encontrar el costo más bajo o el día con peores ventas.

In [9]:
#sacamos el valor mas pequeño, de la matriz ventas_producto, para ver que dia se vendio menos o se gasto menos, segun
#la interpretacion
print(ventas_producto.min())
#nos da 350, podriamos decir que de todos los datos fue el dia que se gasto menos en el costo del producto

350


# Los Ejes o Axis

#### Los ejes o axis, no es mas que una forma de poder seleccionar, las partes de un array 2D o 3D, cuando usamos las funciones de estadistica rapida, al usar funciones como .sum() o .mean(), nos da un resultado global, pero cuando necesitamos obtener el promedio o la suma de una sola columna o renglones, aqui viene esta funcion o truco de los Axis

#### usaremos axis=0, cuando queremos ejecutar la funcion hacia abajo, es decir por columnas, por ejemplo en la matriz ventas_costo, sumamos toda la fila 1, que son las ventas totales de los dos dias, nota ventas total al costo de precio publico, y el total del costo de lo que nos cuesta los productos 

In [10]:
#Recordar la matriz,
# 575, 350
#1120, 680
print(ventas_producto.sum(axis=0))


[1695 1030]


In [12]:
# ahora como lo hacemos por renglon ? axis = 1
print(ventas_producto.sum(axis=1))

[ 925 1800]


# Vectorizacion

#### Llamamos vectorizacion a las operaciones matematicas entre filas y columnas enteras

In [16]:
## para ejemplificar mejor, hagamos el ejemplo de vectorizar para sacar la utilidad bruta de la matriz venta_producto
## Recordar que utilidad bruta es la ganancia que se obtiene al restar los costos
# Columna 0 = Ventas | Columna 1 = Costos
# [575, 350]  <- Día 1
# [1120, 680] <- Día 2

# 1. Separamos las columnas usando Slicing (rebanado)
# El ":" significa "tráeme todas las filas", y el número es el índice de la columna.
ingresos = ventas_producto[:, 0] 
print("Ingresos", ingresos)
costos = ventas_producto[:, 1]
print("costos", costos)

# 2. Operación Vectorizada (La resta mágica)
utilidad_bruta = ingresos - costos

# 3. Vemos el resultado
print("Utilidad Bruta (Día 1, Día 2):", utilidad_bruta)


Ingresos [ 575 1120]
costos [350 680]
Utilidad Bruta (Día 1, Día 2): [225 440]


# Ejercicios

#### Ejercicio 1 ; Tenemos en un negocio de cerveza las ventas de tres tipos diferentes de cerveza (corona extra, victoria y corona light) de los dias con mas movimiento que son los fines de semana, tambien se incluyo el dia jueves.

#### 1. Calcular el total de unidades vendidas por cada dia, (piensa en que axis usar para sumar).
#### 2. Calcula el total de unidades vendidas de cada tipo de cerveza en todo el fin de semana.
#### 3. Encuentra cuál fue el pico máximo de ventas en un solo día.

In [12]:
# mostramos matriz 
import numpy as np

# matriz de ventas del fin de semana 
# filas  = dias 
# columnas = productos (corona light , extra y victoria)
ventas_fin_semana = np.array([
    [15,10,5], #jueves
    [30,20,10], # viernes
    [50,40,20], #sabado
    [25,15,8] #domingo
])
# 1. total de unidades vendidas por dia.
unidades_vendidas = ventas_fin_semana.sum(axis=1)
print("Unidades totales vendias por dia en el orden de jueves a domingo",unidades_vendidas)
print("------------------------------------------------------------------------------------")
#2. Calcular el total de unidades por cada tipo de cerveza en todo el fin se semana 
unidades_vendidas_tipo_cerveza = ventas_fin_semana.sum(axis=0)
print("Unidades vendidas por cada tipo, Corona light, Corona extra y Victoria", unidades_vendidas_tipo_cerveza)

#3. Encuentra cual fue el pico maximo de ventas en un sol dia
print("El producto que mas se vendido un solo dia, fue de corona light y fue el dia sabado", ventas_fin_semana.max())



Unidades totales vendias por dia en el orden de jueves a domingo [ 30  60 110  48]
------------------------------------------------------------------------------------
Unidades vendidas por cada tipo, Corona light, Corona extra y Victoria [120  85  43]
El producto que mas se vendido un solo dia, fue de corona light y fue el dia sabado 50


#### Problema 2, Finanzas del negocio , vamos a calcular el dinero que entró y cuánto costó. Tienes esta segunda matriz con los datos financieros, usemos producto punto


In [22]:
# Filas = Productos (Clara, Oscura, Artesanal) - ¡Deben coincidir con las columnas de ventas!
# Columnas = Precio de Venta, Costo de Compra/Producción
finanzas_cerveza = np.array([
    [40,25], #Corona light
    [45,28], # corona extra
    [65,35] #victoria 
])

# matriz de ventas del fin de semana 
# filas  = dias 
# columnas = productos (corona light , extra y victoria)
ventas_fin_semana = np.array([
    [15,10,5], #jueves
    [30,20,10], # viernes
    [50,40,20], #sabado
    [25,15,8] #domingo
]) 

#1. crea un matrix que muestre los ingresos total y costos totales de 4 dias 
costo_ventas = np.dot(ventas_fin_semana,finanzas_cerveza)
print(costo_ventas)
# NOTA Y REGLA DE ORO, para la funcion np.dot, para acomodar las matrices de forma correcta, las columnas de la matriz A (ventas_fin_semana), que son 3,
# tienen que empatar con los renglones de la matriz B (finanzas_cervezas), es decir matriz A 4x3 y matriz B 3x2, si esos numeros son iguales
# se puede hacer el calculo de la matriz resultante en este caso costo_ventas

print("--------------------")
#2. vectorizacion para sacar utilidad bruta
#primero, nos quedamos con todos los ingresos o ventas
ingresos = costo_ventas[:,0]
print("Ingresos; ",ingresos)
print("---------------------")
costos = costo_ventas[:,1]
print("Costos; ",costos)

#ahora sacamos utilidad bruta
utilidad_bruta = ingresos - costos
print("Utilidad Bruta por dia ", utilidad_bruta)

#ahora sacamos utilidad bruta total
print("Utilidad Bruta total del fin de semana; ",utilidad_bruta.sum())

[[1375  830]
 [2750 1660]
 [5100 3070]
 [2195 1325]]
--------------------
Ingresos;  [1375 2750 5100 2195]
---------------------
Costos;  [ 830 1660 3070 1325]
Utilidad Bruta por dia  [ 545 1090 2030  870]
Utilidad Bruta total del fin de semana;  4535


#### Usa el producto punto (np.dot() o @) entre ventas_fin_semana y finanzas_cerveza para crear una matriz resultante que te muestre los Ingresos Totales y Costos Totales por cada uno de los 4 días.
#### 2. Usando esa matriz resultante y aplicando vectorización (como la resta mágica de tus apuntes), calcula un arreglo final que te dé la utilidad bruta (Ingresos - Costos) de cada día.

#### Ejercicio de logica para entender el flujo de trabajo de la multiplicacion producto punto, la funcion np.dot()

In [25]:
# matriz A pedidos de clientes
#donde filas o renglones = cliente 1 y cliente 2
# donde columnas = unidades light y unidades extra 
pedidos_clientes = np.array ([
    [2,3], #cliente 1, dos unidades light y tres unidades extra
    [4,1] #cliente 2, 4 unidades light y una unidad extra 
])

#matriz B
precio_sucursales = np.array([
    [30,35],# corona light, suc centro vale 30, suc encinos 35
    [40,45] #corona extra, suc centro vale 40, suc encinos 45
])

#si aplicamos una multiplicacion la matriz resultante nos dara, cuanto le cuesta a cada cliente la cerveza en diferente sucursal
# cliente 1 [60, 120] , cliente 2 [120,40]
costo_suc = np.dot(precio_sucursales,pedidos_clientes)
print(costo_suc)
print("----------------------------------------")
costo_suc2 = np.dot(pedidos_clientes, precio_sucursales)
print(costo_suc2)

[[200 125]
 [260 165]]
----------------------------------------
[[180 205]
 [160 185]]


# Ejercicos de tarea 

#### Proyección Cervecera (Semanas vs Finanzas)

#### Vamos a proyectar cómo le iría a tu negocio en las próximas 3 semanas con dos productos estrella.
#### Matriz A (Proyección de Ventas): 3 Semanas x 2 Tipos de Cerveza (Clara, Oscura)
#### Semana 1: 50 Claras, 40 Oscuras
#### Semana 2: 60 Claras, 45 Oscuras
#### Semana 3: 45 Claras, 30 Oscuras


#### Matriz B (Datos Financieros): 2 Tipos de Cerveza x 2 Conceptos (Precio de Venta Público, Costo de Producción)
#### Clara: Se vende a 40, cuesta 25 Oscura: Se vende a 45, cuesta 28

### objetivos; traducir los datos a matrices, definir el orden correcto para la funcion np.dot() y el reto principal , explica por medio de comentarios en tu codigo , donde apliques el truco de interiores y exteriores para explicar que conceptos conforman filas y columnas de la matriz resultante (por ejemplo "la matriz final es de [concepto1] x [concepto2]

In [4]:
import numpy as np
#inciso 1 traducir datos 
# Creamos las matrices 
proyeccion_cervezas = np.array([
    [50,40], #semana 1 , columnas tipo de cerveza clara y obscura
    [60,45], # semana 2
    [45,30] # semana 3
])

# creamos matriz B = datos financieros
datos_financieros = np.array([
    [40,25], #cerveza clara, columnas 1 precio de venta , columna 2 precio de costo
    [45,28] #cerveza obscura
])

#inciso 2, orden correcto en la funcion np.dot() y truco de interiores 
# Comentarios, tenemos dos matrices, matriz proyeccion_cervezas de orden 3x2 = 3 semanas x 2 cervezas (tipos), luego tenemos matriz datos_financieros
# de orden 2x2 = 2 cervezas(tipos) x 2 Precios (venta y costo)
# TRUCO DE INTERIORES 3 semanas x 2 cervezas(tipos), 2 Cervezas(tipos) x 2 Precios = se eliminan los dos tipos de cervezas y la matriz
# resultante es de 3 semanas X 2 precios, con 6 datos, la matriz resultante seria semanas_precios

# funcion np.dot()las columnas de la primera matriz deben representar lo mismo que las filas de la segunda matriz, es decir, cuando apliquemos el truco
# de los interiores, para que hagan clic las dos matrices, es el mismo orden en la funcion.
# el truco del orden, 
semanas_precios = np.dot(proyeccion_cervezas,datos_financieros)
print(semanas_precios)

# CONCEPTOS DE LA MATRIZ RESULTANTE semanas_precios
# los datos que se obtienen es la multiplicacion del costo al publico de la cerveza clara por las unidades que se proyectan vender 
#de la matriz proyeccion_cervezas, asi mismo el proceso para la cerveza obscura, despues ambos resultados de las multiplicaciones se suman 
# lo que nos da 3800, ese dato es la proyeccion de ventas en dinero y el segundo dato del renglon 1 es el lo que cuesta vender ese dia 
# OJO , solo contanto el precio de lo que a negocio le cuesta la cerveza no gastos operativos

#INTERPRETACION; matriz semanas_precios, es filas = semanas , columna 1 = monto de venta y columna 2 = costo de esa venta


[[3800 2370]
 [4425 2760]
 [3150 1965]]


# Ejercicio 2; Expansión a IronForge Gym Store; y, al igual que el anterior, te pide usar el producto punto, pero esta vez enfocado en las finanzas de la tienda de suplementos del gimnasio.

#### Matriz A (Ventas por Sucursal): 2 Sucursales x 3 Productos (Proteína, Creatina, Pre-entreno)
#### Sucursal Norte: 10 Proteínas, 15 Creatinas, 5 Pre-entrenos
#### Sucursal Sur: 8 Proteínas, 20 Creatinas, 10 Pre-entrenos

#### Matriz B (Catálogo de Precios): 3 Productos x 2 Conceptos (Precio Público, Costo de Proveedor)
#### Proteína: Se vende a $800, cuesta $500
#### Creatina: Se vende a $400, cuesta $200
#### Pre-entreno: Se vende a $500, cuesta $300

In [7]:
# inciso 1. #problema producto punt
#creamos matrices
sucursales_productos = np.array([
    [10,15,5], #sucursal norte. columna 1 proteina, columna 2 creatina, columna 3 pre entreno
    [8,20,10] #sucursal sur 
])

catalogo_precios = np.array ([
    [800,500], #proteina
    [400,200], #creatina
    [500,300] #preentrenoo
])

#inciso 2, aplicamos el truco interiores matriz A = 2 sucursales x 3 productos , matriz B = 3 productos x 2 precios, se eliminan productos
# con productos nos queda en conceptos 2 sucursales x 2 precios, matriz resultante secursales_precios
sucursales_precios = np.dot(sucursales_productos,catalogo_precios)
print(sucursales_precios)

#interpretacion de matriz resultante, en base a los conceptos de cada matriz tenemos, que
# la matriz sucursales_precios , es decir, multiplicamos todos los suplementos por su precio y los sumamos
# nos da 16500, ese es el monto de venta, renglon 1 , columna 1 , el siguiente dato en el renglon 1 es lo que nos costo esa venta

# por lo tanto sucursales_precios = renglones sucursales , columna 1 ventas de suplementos, columna 2 costo de la venta de esos suplementos

###############################################################################################################################################
# TEMARIO PENDIENTE DEL PROFESOR


[[16500  9500]
 [19400 11000]]


In [14]:
# --- TEMA: FILTRADO AVANZADO (BOOLEAN INDEXING) ---
# Recordando nuestra matriz resultante: sucursales_precios
# Fila 0: Suc Norte | Fila 1: Suc Sur
# Columna 0: Ventas | Columna 1: Costos.
#Concepto; el filtrado boolean indexing es para filtrar ciertos datos del arreglo, siempre y cuando una "condicion" se cumpla
# por ejemplo; NumPy, tráeme solo los datos donde la venta haya sido mayor a cierto número".

# 1. Primero, vamos a aislar solo la columna de las ventas (Columna 0) usando "slicing"
ventas_totales = sucursales_precios[:,0]
print("Ventas de Ambas sucursales: ,", ventas_totales) # lo esperado debe ser 16500 y 19400

# 2. Creamos la "pregunta" o condición booleana. 
# Supongamos que la meta semanal de la tienda era vender más de 18,000 pesos.
filtro_meta = ventas_totales >= 18000

#3. # 3. Si imprimimos el filtro, NumPy nos devuelve un arreglo de Verdaderos y Falsos (True/False
print(" Se cumplio la meta? ", filtro_meta) 
# Interpretacion del resultado [False  True] (La Norte no, la Sur sí)

# 4. LA MAGIA (Boolean Indexing): Le pasamos ese filtro de True/False al arreglo original
# para que NumPy nos traiga SOLO los números que cumplieron la condición.
ventas_estrella = ventas_totales[filtro_meta] #aqui filtro_meta contiene los true y false, en este caso False , true, por lo tanto 16500 no pasa
# y 19400 si pasa
print("Monto de las ventas que superaron la meta:", ventas_estrella)

Ventas de Ambas sucursales: , [16500 19400]
 Se cumplio la meta?  [False  True]
Monto de las ventas que superaron la meta: [19400]


# Importacion de formatos CSV

In [17]:
import numpy as np
#creamos la variable y usamos la funcion np.genfromtxt
datos_mes = np.genfromtxt('venta_cerveza.csv.txt', delimiter=',', skip_header=1)
# usamos la funcion para que no nos arroje, exponencilaes al momento de imprimir
np.set_printoptions(suppress=True)
# Imprimimos la matriz para ver los datos cargados
print("Matriz de ventas mensuales:\n", datos_mes)

# Y comprobamos la forma para asegurar que son 4 semanas y 3 columnas
print("\nDimensiones:", datos_mes.shape)
print("---------------------------------")
#extraemos los datos del mes con el filtrado booleano, primero aplicamos scling, para extraer las ventas solamente de la matriz
ventas_mayores = datos_mes[:,1]
filtro_ventas = ventas_mayores > 10000
mejores_ventas = ventas_mayores[filtro_ventas]
print("Estas fueron las ventas que superaron los 10,000; ",mejores_ventas)


Matriz de ventas mensuales:
 [[    1. 10500.  4000.]
 [    2.  9800.  3500.]
 [    3. 11200.  4200.]
 [    4.  8500.  3000.]]

Dimensiones: (4, 3)
---------------------------------
Estas fueron las ventas que superaron los 10,000;  [10500. 11200.]


#### Limpieza y analisis, funciion np.unique, esta funcion es una de las herramientas mas poderosas de numpy, basicamente su resume datos repetidos 

#### Primer obtiene valores unicos, aqui revisa todo el arreglo y te devuelve valores distintos, eliminando cualquier repeticion

#### Calcula frecuencias absolutas, le agregas un parametro al codigo, hace el conteo matematico de cuantas veces se repite un dato 
#### en el arreglo o tu dataset

#### Veamos un ejemplo basico

In [22]:
# creamos un arreglo para tipos de cerveza
import numpy as np
cervezas = np.array(['Stout', 'IPA', 'Lager', 'IPA', 'Stout', 'IPA'])
np.unique(cervezas) #el resultado es acomodado de la A a la Z, en el resultado solo obtener los estilos de cervezas

#Como obtenemos las frecuencias absolutas ? 
# que son las frecuencias absolutas ? el numero de veces que se repite un dato en un conjunto
# Encendemos el switch "return_counts=True" para que NumPy cuente las repeticiones
estilos_distintos, conteo_ventas = np.unique(cervezas, return_counts=True)

#que pasa en a linea de codigo de arriba, la funcion unique la divimos en dos partes una para que nos entregue los datos =estilos distintos
# otra para que nos de las veces que contro ese dato, = conteo de ventas
# recuerda que las variables de asignan hacia el lado izquierdo, o se leen hacia el lado izquierdo
#por eso en ese codigo tienes dos variables estilos_distintos y conteo_ventas

print("Estilos vendidos:", estilos_distintos)
print("Piezas por estilo:", conteo_ventas)

Estilos vendidos: ['IPA' 'Lager' 'Stout']
Piezas por estilo: [3 1 2]
