# Vector 1D


 ## Primero, siempre importar la libreria numpy

In [1]:
import numpy as np

### un ndarray es la unidad minima con la que trabaja numpy, pero los ndarray o arreglos en español, pueden ser diferentes tipos de unidades, que son vectores, que suelen ser de una dimension (1d), las matrices (2d) y tensores (3d), AQUI comenzamos con los vectores, que es un conjunto de numeros entre parentesis o corchetes, pueden tener n cantidad de datos


In [2]:
# como creamos un vector, en numpy ? , la respuesta es facil, creamos una variable y llamamos a la funcion np.array ([datos]).
vector = np.array([25,1,69])


## Tenemos funciones en los ndarrays del tipo vector (1d), las primeras funciones que tenemos, son .shape, .size y d.type, todas estas nos sirven para desglosar el tipo de dato del vector, para numpy eso es importante, comenzemos con la funcion .shape y d.type

In [5]:
# La funcion .shape es lo mismo a la funcion .len en python, .shape, hace que numpy nos diga cuantos datos tiene el vector,
#o dicho de otra forma, la estructura dimensional, cuando ejecutamos la funcion .shape, nos devuele un tupla indicanto cuantos elementos existen
vector.shape


(3,)

In [4]:
# Si te fijas al ejecutar la funcion el resultado es (3,) esto significa que existen tres datos en esta dimension
# la coma vacia es decir (, ) significa que no hay otra dimension, esto porque porque es un vector y este es de una sola dimension
# contrario a las matrices, en ese caso si seria por ejemplo (3,6) 


In [5]:
#Ahora vamos con la funcion d.type, esta funcion es importante,
# d.type, significa "DATA TYPE" , lo que hace la funcion es hacer homogeneo todos los datos, por ejemplo
import numpy as np
vector1= np.array([25,2,69])
print("tipo 1",vector1.dtype)


tipo 1 int64


In [ ]:
# cuando son enteros, el tipo de dato es un int64


In [7]:
vector2_mezclado = np.array([10,11,9.5])
print("Tipo 2, mezclado, viene un decimal en los vectores",vector2_mezclado.dtype)


Tipo 2, mezclado, viene un decimal en los vectores float64


In [ ]:
# el tipo es de float64


In [8]:
vector_forzado = np.array([1, 2, 3], dtype=np.int8)
print("Tipo Forzado:", vector_forzado.dtype)

Tipo Forzado: int8


In [ ]:
#cambio de un int64 del tipo 1 o entero a un int8, recuerda que los tipos son ligados a los bits, pero si son tipos de datos
#pueden ser enteros o decimales (float)
#para eso sirve la funcion o el atributo d.type, su funcion TODO EN EL VECTOR LO CONVIERTE AL MISMO TIPO DE DATO


## Atributo .Size

## El atributo .size es muy parecido a al atributo .shape, mientras .shape te da las dimenciones y el numero de datos en esa dimencion,porque el vector es de una sola dimension, el .size es mas directo te dice exactamente cuántos elementos individuales viven adentro de esa estructura, sin importar su forma.


In [9]:
vector4 = np.array([25,48,59])
vector4.size

3

In [ ]:
# solo imprime tres, sin como o entre corchetes, solo te da el numero


# Indexing y Slicing

### Es una habilidad , que se usa en ciencia de datos, consiste en extraer datos especificos del vector, matriz o tipo de array con el que se trabaje, el indexing basicamente es extraer un solo dato del array, SOLO UNO, aqui aplicamos cierta sintaxis parecidas a las listas de python, como regla de oro; comenzamos a contar de cero no del uno

In [11]:
# veamos algun ejemplo 
vector_max = np.array([10,20,30,85,78,45])
#aplicamos el indexing, extraemos un solo valor, supongamos el 85
vector_max[3] #Esta es la sintaxis para extraer, muy similar a las listas
# o aplicamos un print
print("extramos el dato, numero 3; ", vector_max[3])


extramos el dato, numero 3;  85


In [13]:
#SLICING o rebanado, es lo mismo que el indexing o indexado, solo con la diferencia que aqui no extraemos solo un dato,
# es decir extraemos un bloque que son varios datos
#supongamos que queremos extraer los primeros 4 datos del vector
print("Los primeros 4 datos del vector: ",vector_max[:4])
#revisa biien la sintaxis, esta linea de codigo es cuando quieres los
#datos del primero al 4, python cuenta de cero no de 1,
#numpy asume que es desde cero por eso se omit escribirlo

Los primeros 4 datos del vector:  [10 20 30 85]


In [15]:
#Ahora veamos un ejemplo donde queremos del valor 4 hasta el final
print("Los ultimos 2 numeros del vector: ", vector_max[4:])

Los ultimos 3 numeros del vector:  [78 45]


In [16]:
#si quieres incluir el 85
print("los ultimos 3 valores del vector: ", vector_max[3:])

los ultimos 3 valores del vector:  [85 78 45]


In [17]:
#veamos mas ejemplos, del indice 1 al 4
vector_max[1:4]

array([20, 30, 85])

In [ ]:
#Si te fijas el ultimo valor o indice 4 no lo imprime, imprine hasta el valor 3,
#pero si imprime el indice 1 o valor 1 que es 20

In [18]:
#TRUCO DEL SALTO; formula [inicio:fin:salto] igual que en python, recuerda el vector [10,20,30,85,78,45]
vector_max[:5:2]

array([10, 30, 78])

In [19]:
vector_datos = np.array([10, 20, 30, 40, 50, 60])
#imprimimos del indice 1 al 4
vector_datos[1:4]

array([20, 30, 40])